keys_to_rename = {
    'Adaptation by': 'writer', 
    'Based on': 'based_on', 
    'Box office': 'box_office', 
    'Budget': 'budget', 
    'Cinematography': 'cinematographer', 
    'Composer(s)': 'composer', 
    'Country': 'country', 
    'Country of origin': 'country', 
    'Directed by': 'director', 
    'Director': 'director', 
    'Distributed by': 'distributor', 
    'Distributor': 'distributor', 
    'Edited by': 'editor', 
    'Editor(s)': 'editor', 
    'Length': 'runtime', 
    'Music by': 'composer', 
    'Original release': 'release_date',
    'Produced by': 'producer', 
    'Producer': 'producer', 
    'Producer(s)': 'producer', 
    'Release date': 'release_date', 
    'Released': 'release_date', 
    'Running time': 'runtime', 
    'Screen story by': 'writer', 
    'Screenplay by': 'writer', 
    'Starring': 'stars',
    'Story by': 'writer', 
    'Theme music composer': 'composer', 
    'Written by': 'writer', 
    'imdb_link': 'imdb_link', 
    'title': 'title',
    'url': 'url', 
    'year': 'year'
}